detect_pth: weights/craft_mlt_25k.pth
text_threshold: 0.7
low_text: 0.5
link_threshold: 0.4
cuda: False
canvas_size: 1280
mag_ratio: 1.5
refine: True
refine_pth: weights/craft_refiner_CTW1500.pth
mask_contour: True
recog_pth: weights/transformerocr.pth